### ISSUE TITLE
Methodology BEM

### ISSUE THREAD

**Issue by brunowego** [rendro/easy-pie-chart#152]
Add class for canvas will help with BEM methodology:

``` html
<ul class="u-list u-list--inline">
  <li class="u-list__item c-chart-pie" data-percent="73">73%</li>
</ul>
```

``` css
.c-chart-pie {
  height: 110px;
  line-height: 110px;
  position: relative;
  text-align: center;
  width: 110px;
}

.c-chart-pie__canvas {
  left: 0;
  position: absolute;
  top: 0;
}
```
