### ISSUE TITLE
How can i set to max value show me full bar as like as 100%

### ISSUE THREAD

**Issue by ozgurkalyoncu** [rendro/easy-pie-chart#68]
Hello friend

i just want to change 100% percent 
how can i set it to 20

example if my value is 20 it shall show it is 100%

**Comment by ghost** [comment]
If you want to update the upper bound of the chart but still maintain control of the detailed value shown see the following.

In my case, I wanted the control to have a range from 0-10 (e.g a value of 5 would result in the control being 50% full). The advice above will update the scale, but also the value being displayed (e.g. 5/10 -> 50/100. If you want to maintain the value (5) but adjust the scale (100->10), see the following. 

Note, I've also included a sample of how to update the value color separately from the control color. If you'd like to add units or additional content to the value see the 'content' option for the percent:after css class below.

```css
.simple-pie {
    position: relative;
    display: inline-block;
    width: 110px;
    height: 110px;
    margin-top: 5px;
    margin-bottom: 5px;
    text-align: center
}
.simple-pie canvas {
    position: absolute;
    top: 0;
    left: 0;
}
.percent {
    display: inline-block;
    line-height: 110px;
    z-index: 2;
}
.percent:after {
    content: "";
    margin-left: .1em;
    font-size: .8em;
}
```

```html
<script src="jquery.easypiechart.min.js"></script>

<span id="gauge" class="simple-pie" data-percent="100">
    <span id="gauge-value" class="percent"></span>
</span>
```

```js
      var cur = foo();
      var scaledValue = (100 * cur / 10);
      var elem = $("#gauge");
      if (elem) {
        elem.easyPieChart({
            animate: 2000,
            barColor: "#26B99A",
            trackColor: "#D3D3D3",
            scaleColor: false,
            lineWidth: 20,
            trackWidth: 16,
            lineCap: "butt",
            percent: scaledValue,
            onStep: function (from, to, percent) {
                $(this.el).find('.percent').text(Number((percent / 10).toFixed(1)));
            }
        });

        setTimeout(function() {
            elem.data("easyPieChart").update(scaledValue);
        }, 1000);

        $("#gauge-value").css("color", getRiskScoreColor(cur));
      }
```
